# Generated by Django 3.0.6 on 2020-06-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200601_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('Question', models.TextField(max_length=200)),
                ('priority', models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('M', 'Med')], max_length=1)),
            ],
        ),
    ]
